id: P010472
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN6952
  title: ཁོར་ཡུག་སྲུང་སྐྱོབ་ཀྱི་ཤེས་བྱའི་ཟེགས་མ།
  author: ''
  volumes:
    885b291421a6479bba56fefa1b64b4a5:
      image_group_id: I3CN6954
      title: ''
      volume_number: 1
      total_pages: 104
      base_file: v001.txt
